### PR TITLE
Add tests for balloon_hash and balloon_m_hash.

### PR DESCRIPTION
**Pull request by elliotwutingfeng**
## Changes

- Add tests for balloon_hash and balloon_m_hash.
- Exclude `if __name__ == .__main__.:` section from unittest

Test coverage is now **100%**

### CODE REVIEW

**Comment by daxpedda** [comment]
As far as I understand the `balloon_hash` and `balloon_m_hash` function just translates the output to HEX.

Instead of using different test vectors, it would be better if we just compare them to the same test vectors but just hex those, right now this is just a ton of duplication.

I would also appreciate if we keep the formatting to a separate PR, is there some official Python formatting tool?

**Comment by elliotwutingfeng** [comment]
Re-using the existing test vectors. I've undone the formatting also.

There is no official Python formatting tool. I would recommend using [black](https://github.com/psf/black) as a code formatter. If you are okay with that I'd open another PR.

**Comment by daxpedda** [comment]
Thanks!

So after playing around a bit I realized that my original statement was not correct, there is a big difference between the `balloon(_m)` and `balloon(_m)_hash` functions, the hashed version doesn't only apply a hex at the end but also doesn't take any parameters for time, space and parallel cost.

Which means that using these test vectors is really pointless.
I would suggest the following: just add a round-trip test, for these functions. Basically you can re-use the test vector data and just feed it into the `balloon(_m)` function with the cost parameters used in the `balloon(_m)_hash` function and then compare the output with each other.

Thank you for working on this!

**Comment by daxpedda** [comment]
Thank you, that was great!

If you would like to make another PR with the formatting you are welcome to do so!

**Pull request merged**
